call ncu -k transpose --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_dadd_pred_on.sum,smsp__sass_thread_inst_executed_op_dfma_pred_on.sum,smsp__sass_thread_inst_executed_op_dmul_pred_on.sum,dram__bytes.sum,dram__bytes_read.sum,dram__bytes_write.sum,l1tex__t_bytes.sum,lts__t_bytes.sum,sm__cycles_elapsed.avg,sm__cycles_elapsed.avg.per_second,smsp__sass_thread_inst_executed_op_integer_pred_on.sum,sm__inst_executed_pipe_alu --log-file transpose-64-32-2048.txt --set default CudaRun.exe -k transpose -b 64 -t 32 -r 2048

call ncu -k sgemm --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_dadd_pred_on.sum,smsp__sass_thread_inst_executed_op_dfma_pred_on.sum,smsp__sass_thread_inst_executed_op_dmul_pred_on.sum,dram__bytes.sum,dram__bytes_read.sum,dram__bytes_write.sum,l1tex__t_bytes.sum,lts__t_bytes.sum,sm__cycles_elapsed.avg,sm__cycles_elapsed.avg.per_second,smsp__sass_thread_inst_executed_op_integer_pred_on.sum,sm__inst_executed_pipe_alu --log-file sgemm-64-32-2048.txt --set default CudaRun.exe -k sgemm -b 64 -t 32 -r 2048

call ncu -k dgemm --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_dadd_pred_on.sum,smsp__sass_thread_inst_executed_op_dfma_pred_on.sum,smsp__sass_thread_inst_executed_op_dmul_pred_on.sum,dram__bytes.sum,dram__bytes_read.sum,dram__bytes_write.sum,l1tex__t_bytes.sum,lts__t_bytes.sum,sm__cycles_elapsed.avg,sm__cycles_elapsed.avg.per_second,smsp__sass_thread_inst_executed_op_integer_pred_on.sum,sm__inst_executed_pipe_alu --log-file dgemm-64-32-2048.txt --set default CudaRun.exe -k dgemm -b 64 -t 32 -r 2048

call ncu -k blur3x3 --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_dadd_pred_on.sum,smsp__sass_thread_inst_executed_op_dfma_pred_on.sum,smsp__sass_thread_inst_executed_op_dmul_pred_on.sum,dram__bytes.sum,dram__bytes_read.sum,dram__bytes_write.sum,l1tex__t_bytes.sum,lts__t_bytes.sum,sm__cycles_elapsed.avg,sm__cycles_elapsed.avg.per_second,smsp__sass_thread_inst_executed_op_integer_pred_on.sum,sm__inst_executed_pipe_alu --log-file blur3x3-64-32-2048.txt --set default CudaRun.exe -k blur3x3 -b 64 -t 32 -r 2048 -s 1

call ncu -k blur9x9 --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_dadd_pred_on.sum,smsp__sass_thread_inst_executed_op_dfma_pred_on.sum,smsp__sass_thread_inst_executed_op_dmul_pred_on.sum,dram__bytes.sum,dram__bytes_read.sum,dram__bytes_write.sum,l1tex__t_bytes.sum,lts__t_bytes.sum,sm__cycles_elapsed.avg,sm__cycles_elapsed.avg.per_second,smsp__sass_thread_inst_executed_op_integer_pred_on.sum,sm__inst_executed_pipe_alu --log-file blur9x9-64-32-2048.txt --set default CudaRun.exe -k blur9x9 -b 64 -t 32 -r 2048 -s 4

call ncu -k blurMxM --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_dadd_pred_on.sum,smsp__sass_thread_inst_executed_op_dfma_pred_on.sum,smsp__sass_thread_inst_executed_op_dmul_pred_on.sum,dram__bytes.sum,dram__bytes_read.sum,dram__bytes_write.sum,l1tex__t_bytes.sum,lts__t_bytes.sum,sm__cycles_elapsed.avg,sm__cycles_elapsed.avg.per_second,smsp__sass_thread_inst_executed_op_integer_pred_on.sum,sm__inst_executed_pipe_alu --log-file blurMxM-64-32-2048.txt --set default CudaRun.exe -k blurMxM -b 64 -t 32 -r 2048 -s 7